In [2]:
import numpy as np

In [ ]:
''' 
init ndarray
'''
arr1 = np.array([1,2,3,4])
print(arr1, type(arr1))
arr2 = np.zeros([2,2,3], dtype=np.float32)
print(arr2)
arr3 = np.arange(1, 10)
print(arr3)


[1 2 3 4] <class 'numpy.ndarray'>
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
''' 
modify ndarray
'''
print(1 + arr3)
print(1 / arr3)
# calculates the exponential e**x
print(np.exp(1))
print(np.exp(arr3))

[ 2  3  4  5  6  7  8  9 10]
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]
2.718281828459045
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [21]:
'''  
reshape ndarray
'''
arr4 = np.array([1,2,3,4])
print(arr4)
print(arr4.shape)
arr5 = arr4.reshape(2, 2)
print(arr5.shape)

[1 2 3 4]
(4,)
(2, 2)
